-- Inserção de Cliente
INSERT INTO cliente (skCliente, "Cód Cliente", "Cliente (Atual)", "Rede (Atual)", "Associação (Atual)", "UF Cliente (Atual)", "Setor (Atual)", "Supervisor (Atual)", "Desc Gerente (Atual)", "Gerente (Atual)", "Desc Divisional (Atual)", "Desc Superintendência (Atual)", "Bairro (Atual)", "Data Últ Compra", "Cód Grupo SAP", "Cód Grupo SAP (Atual)", "Micro Região (Atual)", "CNPJ/CPF (Atual)", "Meso Região (Atual)", "Desc Segmentação Cliente (Atual)", "Desc Grupo Prazo Cliente (Atual)", "Indicador Controlado (Atual)")
VALUES (1, 123, 'Cliente A', 'Rede A', 'Associação A', 'SP', 'Setor A', 'Supervisor A', 'Gerente A', 'Gerente Atual A', 'Divisão A', 'Superintendência A', 'Bairro A', '2023-01-01', 'Grupo SAP A', 'Grupo SAP Atual A', 'Micro Região A', '12345678900', 'Meso Região A', 'Segmentação A', 'Prazo Cliente A', 'Sim');

INSERT INTO cliente (skCliente, "Cód Cliente", "Cliente (Atual)", "Rede (Atual)", "Associação (Atual)", "UF Cliente (Atual)", "Setor (Atual)", "Supervisor (Atual)", "Desc Gerente (Atual)", "Gerente (Atual)", "Desc Divisional (Atual)", "Desc Superintendência (Atual)", "Bairro (Atual)", "Data Últ Compra", "Cód Grupo SAP", "Cód Grupo SAP (Atual)", "Micro Região (Atual)", "CNPJ/CPF (Atual)", "Meso Região (Atual)", "Desc Segmentação Cliente (Atual)", "Desc Grupo Prazo Cliente (Atual)", "Indicador Controlado (Atual)")
VALUES (3, 789, 'Cliente B', 'Rede B', 'Associação B', 'MG', 'Setor B', 'Supervisor B', 'Gerente B', 'Gerente Atual B', 'Divisão B', 'Superintendência B', 'Bairro B', '2023-03-01', 'Grupo SAP B', 'Grupo SAP Atual B', 'Micro Região B', '98765432101', 'Meso Região B', 'Segmentação B', 'Prazo Cliente B', 'Sim');

-- Inserção de Produtos
INSERT INTO produto (skProduto, "Cód Produto", "Desc Produto (Atual)", Produto, "Produto (Atual)", "SubSortimento (Atual)", "Cód Fornecedor (Atual)", "Desc Chaveamento Fornecedor (Atual)", "SSF Chaveamento Fornecedor (Atual)", "Desc Marca (Atual)", "Cód Barra EAN (Atual)", "Cód Barra EAN", "Indicador Monitorado (Atual)", "Indicador Importado (Atual)", "Cód Origem (Atual)", "Desc Categoria Comercial (Atual)", "Categoria Comercial (Atual)", "Desc Sazonalidade (Atual)", "Cód Condição Estocagem (Atual)", "Desc Marca Arvore Mercadológica (Atual)", "Comprador Atacado (Atual)", "Cód Grupo Preço (Atual)", "Cód Curva Preço (Atual)", "Coordenador Atacado (Atual)", "Coordenador Varejo (Atual)")
VALUES (1, 12345, 'Descrição do Produto A', 'Produto A', 'Produto Atual A', 'Sortimento A', 789, 'Fornecedor A', 'SSF A', 'Marca A', 111222333, 444555666, 'Sim', 'Não', 101, 'Categoria A', 'Categoria Atual A', 'Sazonalidade A', 'Condição A', 'Marca Árvore A', 'Comprador A', 102, 'Curva A', 'Coordenador A', 'Coordenador Varejo A');

INSERT INTO produto (skProduto, "Cód Produto", "Desc Produto (Atual)", Produto, "Produto (Atual)", "SubSortimento (Atual)", "Cód Fornecedor (Atual)", "Desc Chaveamento Fornecedor (Atual)", "SSF Chaveamento Fornecedor (Atual)", "Desc Marca (Atual)", "Cód Barra EAN (Atual)", "Cód Barra EAN", "Indicador Monitorado (Atual)", "Indicador Importado (Atual)", "Cód Origem (Atual)", "Desc Categoria Comercial (Atual)", "Categoria Comercial (Atual)", "Desc Sazonalidade (Atual)", "Cód Condição Estocagem (Atual)", "Desc Marca Arvore Mercadológica (Atual)", "Comprador Atacado (Atual)", "Cód Grupo Preço (Atual)", "Cód Curva Preço (Atual)", "Coordenador Atacado (Atual)", "Coordenador Varejo (Atual)")
VALUES (2, 12345, 'Descrição do Produto B', 'Produto B', 'Produto Atual B', 'Sortimento B', 789, 'Fornecedor B', 'SSF B', 'Marca B', 111222333, 444555666, 'Sim', 'Não', 101, 'Categoria B', 'Categoria Atual B', 'Sazonalidade B', 'Condição B', 'Marca Árvore B', 'Comprador B', 102, 'Curva B', 'Coordenador B', 'Coordenador Varejo B');

INSERT INTO produto (skProduto, "Cód Produto", "Desc Produto (Atual)", Produto, "Produto (Atual)", "SubSortimento (Atual)", "Cód Fornecedor (Atual)", "Desc Chaveamento Fornecedor (Atual)", "SSF Chaveamento Fornecedor (Atual)", "Desc Marca (Atual)", "Cód Barra EAN (Atual)", "Cód Barra EAN", "Indicador Monitorado (Atual)", "Indicador Importado (Atual)", "Cód Origem (Atual)", "Desc Categoria Comercial (Atual)", "Categoria Comercial (Atual)", "Desc Sazonalidade (Atual)", "Cód Condição Estocagem (Atual)", "Desc Marca Arvore Mercadológica (Atual)", "Comprador Atacado (Atual)", "Cód Grupo Preço (Atual)", "Cód Curva Preço (Atual)", "Coordenador Atacado (Atual)", "Coordenador Varejo (Atual)")
VALUES (3, 12345, 'Descrição do Produto C', 'Produto C', 'Produto Atual C', 'Sortimento C', 789, 'Fornecedor C', 'SSF C', 'Marca C', 111222333, 444555666, 'Sim', 'Não', 101, 'Categoria C', 'Categoria Atual C', 'Sazonalidade C', 'Condição C', 'Marca Árvore C', 'Comprador C', 102, 'Curva C', 'Coordenador C', 'Coordenador Varejo C');
